# This will build an xRegistry dev env image.
# It serves two purposes:
# 1 - shows the minimal steps necessary to build, test, run this repo
# 2 - people can use this as a docker dev environment if they want one

FROM golang:alpine

LABEL org.opencontainers.image.source https://github.com/xregistry/server

ARG GIT_COMMIT

# Minimal tools - docker is just for the client, it assumes we'll use the
# docker running on the host due to --network host on the "docker run"
RUN apk add make git bash docker

# Clone the repo. Don't actually do it since we want to test changes to make
# sure it didn't break anything. However, normally you'll want to use this
# 'clone' command instead of the 'COPY' below.
# WORKDIR /go/src/github.com/xregistry
# git clone https://github.com/xregistry/server.git

# Copy our repo (comment this section out if the above section is enabled)
WORKDIR /go/src/github.com/xregistry/server
COPY . ./

# Erase any built files from the COPY so we have a clean env
RUN make clean

# Pull down all of the go packages just so we don't need to do it later
RUN go get ./...
