#!/bin/sh

export DBHOST=${DBHOST:-127.0.0.1}
export DBPORT=${DBPORT:-3306}
export DBUSER=${DBUSER:-root}
export DBPASSWORD=${DBPASSWORD:-password}

export MYSQL_ROOT_PASSWORD=${DBPASSWORD}

export XR_MODEL_PATH=${XR_MODEL_PATH:-/spec}

set -ex

env | grep -v PASS | sort

if [[ "$1" == "--db" ]]; then
  docker-entrypoint.sh mysqld &
  /waitformysql
  shift
elif [[ "$1" == "db" ]]; then
  docker-entrypoint.sh mysqld
  exit 0
fi

/server $*
